version: '3.8'

services:
  # Frontend service with conditional Nginx handling
  frontend:
    build:
      context: ..
      dockerfile: production/Dockerfile
    container_name: chat-app-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
      - VITE_SOCKET_URL=${VITE_SOCKET_URL:-http://localhost:3000}
      - VITE_APP_NAME=${VITE_APP_NAME:-Chat App}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - BACKEND_HOST=${BACKEND_HOST:-host.docker.internal}
      - BACKEND_PORT=${BACKEND_PORT:-3002}
    volumes:
      # Mount nginx config (optional - can be built into image)
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Conditional startup script
    command: >
      sh -c "
        echo 'Checking for existing Nginx installation...';
        if command -v nginx >/dev/null 2>&1; then
          echo 'Nginx detected on host system';
          echo 'Running in proxy mode - using host Nginx configuration';
          # Use host nginx config
          cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.backup;
          echo 'Frontend container ready for host Nginx proxy';
          # Keep container running but don't start nginx
          tail -f /dev/null;
        else
          echo 'No Nginx detected on host system';
          echo 'Running in standalone mode with built-in Nginx';
          echo 'Starting built-in Nginx server...';
          nginx -g 'daemon off;';
        fi
      "

  # Optional: Nginx proxy service (only if host doesn't have nginx)
  nginx-proxy:
    image: nginx:alpine
    container_name: chat-app-nginx-proxy
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL certificates (optional)
    networks:
      - chat-network
    depends_on:
      - frontend
    restart: unless-stopped
    profiles:
      - proxy  # Only start when explicitly requested
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  chat-network:
    driver: bridge
    external: false

# No persistent volumes needed for frontend
