version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:3001/api
      - VITE_SOCKET_URL=http://localhost:3001
      - VITE_APP_NAME=Chat App
      - VITE_APP_VERSION=1.0.0
    depends_on:
      - backend
    networks:
      - chat-network

  # This would be your backend service
  # backend:
  #   build: ../backend
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     - NODE_ENV=production
  #     - DATABASE_URL=your_database_url
  #   networks:
  #     - chat-network

networks:
  chat-network:
    driver: bridge
